### ISSUE TITLE
HDMI switches in juno-monitor are never reached

### ISSUE THREAD

**Issue by EX0l0N** [junocomp/debian-juno-tablet#1]
https://github.com/junocomp/debian-juno-tablet/blob/0fad62b23823767465101f1b58dea5211cf344c1/juno-monitor#L4-L5

Two variables defined for HDMI (dis)connect events are never used. All three blocks use the `$dp` variable.

(Still true for `main`, I have no idea why I was on that commit.)

**Comment by junocomp** [comment]
Thanks for noticing, fixed
